# Generated by Django 4.1.3 on 2023-07-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('image', models.ImageField(upload_to='static/upload/banner/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '广告图',
                'verbose_name_plural': '广告图',
            },
        ),
    ]
